del /s /F *.aux
del /s /F *.bcf
del /s /F *.idx
del /s /F *.log
del /s /F *.run.xml
del /s /F *.out
del /s /F *.toc
del /s /F *.thm
del /s /F *.ilg
del /s /F *.ind
del /s /F *.synctex.gz
del /s /F *.fdb_latexmk
del /s /F *.bbl
del /s /F *.fls
del /s /F *.ilg
del /s /F *.blg
del /s /F *.pytxcode
del /s /F *.listing
del /s /F *.xdv
FOR /D /R %%X IN (_minted-*) DO RD /S /Q "%%X"