defaultIndent: "    "
onlyOneBackUp: 1
noAdditionalIndent:
    item: 1
lookForAlignDelims:
    tabvar: 1
verbatimEnvironments:
    code: 1
    pycode: 1
    minted: 1
indentAfterHeadings:
    part:
        indentAfterThisHeading: 1
        level: 1
    chapter:
        indentAfterThisHeading: 1
        level: 2
    section:
        indentAfterThisHeading: 1
        level: 3
    subsection:
        indentAfterThisHeading: 1
        level: 4
    subsubsection:
        indentAfterThisHeading: 1
        level: 5
    paragraph:
        indentAfterThisHeading: 1
        level: 6
indentRules:
    section: "    "
    chapter: "    "
    part: "    "
    subsection: "    "
    subsubsection: "    "
    paragraph: "    "